/*
 * cmd/antsd/config.h — antsd node configuration (CBOR on disk).
 *
 * The daemon's persistent config: the node's Ed25519 identity seed, the
 * listen multiaddr, and the bootstrap seed peers. Generated by `antsd
 * init` and read by `antsd show` / `antsd run`. Encoded as canonical
 * CBOR (RFC-0008 §1.1) via foundation/cbor, so the on-disk form is the
 * same deterministic encoding the protocol uses everywhere else — at the
 * cost of not being hand-editable, which is what `antsd show` is for.
 */
#ifndef ANTSD_CONFIG_H
#define ANTSD_CONFIG_H

#include "ants_common.h"
#include "ants_crypto.h" /* ANTS_ED25519_{PRIVKEY,PUBKEY}_SIZE */

#include <stddef.h>
#include <stdint.h>

/* Max multiaddr length incl. the NUL terminator. Mirrors the transport's
 * own multiaddr bound (/ip4|ip6/.../udp/<port>/quic-v1 + /p2p/<base58> has
 * margin under this). */
#define ANTSD_MULTIADDR_MAX 128
#define ANTSD_MAX_SEEDS     16

typedef struct {
    char addr[ANTSD_MULTIADDR_MAX];            /* seed multiaddr (NUL-terminated) */
    uint8_t peer_id[ANTS_ED25519_PUBKEY_SIZE]; /* expected Ed25519 peer id */
} antsd_seed_t;

typedef struct {
    /* Ed25519 private seed — the node's identity. Held only by the daemon
     * and exposed to the transport solely through a sign callback. */
    uint8_t identity_priv[ANTS_ED25519_PRIVKEY_SIZE];
    char listen_multiaddr[ANTSD_MULTIADDR_MAX]; /* "" => dial-only */
    antsd_seed_t seeds[ANTSD_MAX_SEEDS];
    size_t seed_count;
} antsd_config_t;

/*
 * Encode `cfg` as canonical CBOR into `buf` (capacity `cap`); the encoded
 * length is written to `*out_len`. Returns ANTS_ERROR_INVALID_ARG on a NULL
 * argument or a config that violates the bounds (seed_count, unterminated
 * strings), or ANTS_ERROR_BUFFER_TOO_SMALL if `cap` is insufficient.
 */
ants_error_t
antsd_config_encode(const antsd_config_t *cfg, uint8_t *buf, size_t cap, size_t *out_len);

/*
 * Decode canonical CBOR from `buf` (`len` bytes) into `*out`. Strict: any
 * structural deviation, non-canonical encoding, out-of-bounds count, wrong
 * field size, or over-long string is rejected (ANTS_ERROR_MALFORMED /
 * NON_CANONICAL). `*out` is fully overwritten on success.
 */
ants_error_t antsd_config_decode(const uint8_t *buf, size_t len, antsd_config_t *out);

/* Upper bound on the encoded size of any valid antsd_config_t. */
#define ANTSD_CONFIG_ENCODED_MAX                                                                   \
    (16 + ANTS_ED25519_PRIVKEY_SIZE + ANTSD_MULTIADDR_MAX +                                        \
     ANTSD_MAX_SEEDS * (8 + ANTSD_MULTIADDR_MAX + ANTS_ED25519_PUBKEY_SIZE))

#endif /* ANTSD_CONFIG_H */
